[package]
name = "derivefmt-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.1", features = ["derive"] }
glob = "0.3"
rayon = "1.6"
derivefmt-core = { path = "../derivefmt-core" }