name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule: [cron: "0 5 * * 1"]

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --verbose

  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt -- --check

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ['rust-lang/rustfmt']
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'derivefmt'
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v3
        with:
          repository: ${{ matrix.target }}
          path: 'testcase'
      - name: Format and build
        run: |
          cd derivefmt
          cargo run --bin cargo-derivefmt -- --file ../testcase
          cd ../testcase
          cargo build

  integration-serde:
    name: Integration Tests (serde-rs/serde)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'derivefmt'
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v3
        with:
          repository: serde-rs/serde
          path: 'testcase'
      - name: Format and build
        run: |
          cd derivefmt
          cargo run --bin cargo-derivefmt -- --file ../testcase/serde
          cd ../testcase/serde
          cargo build --no-default-features
  
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - run: cargo clippy -- -Dwarnings

  outdated:
    name: Outdated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/install@cargo-outdated
      - run: cargo outdated --workspace --exit-code 1
